export const siteConfig = {
  name: "Great 20 Sacco",
  shortName: "G20 Sacco",
  description: "A modern digital branch for membership, savings, borrowing guidance and support.",
  locale: "en_KE",
  currency: "KES",
  contact: {
    phoneLabel: "Official phone available before launch",
    emailLabel: "Official email available before launch",
    addressLabel: "Verified branch details available before launch",
  },
  features: {
    askG20: true,
    applications: true,
    payments: true,
    liteMode: true,
  },
  notices: [
    {
      id: "demo-service-notice",
      label: "Demo environment",
      message: "You are viewing a frontend demonstration. No real applications, documents or payments are processed.",
    },
  ],
} as const;

export const primaryNav = [
  { label: "Membership", href: "/membership" },
  { label: "Save", href: "/save" },
  { label: "Borrow", href: "/borrow" },
  { label: "Services", href: "/services" },
  { label: "Resources", href: "/learn" },
  { label: "About", href: "/about" },
  { label: "Help", href: "/help" },
] as const;

export const routeLabels: Record<string, string> = {
  membership: "Membership",
  save: "Save",
  borrow: "Borrow",
  compare: "Compare products",
  calculators: "Calculators",
  "ask-g20": "Ask G20",
  services: "Services",
  learn: "Financial education",
  blog: "Blog",
  news: "Newsroom",
  events: "Events",
  notices: "Notices",
  media: "Media centre",
  stories: "Member stories",
  transparency: "Transparency",
  reports: "Reports",
  downloads: "Downloads",
  branches: "Branches",
  security: "Security centre",
  about: "About G20",
  careers: "Careers",
  procurement: "Procurement",
  partners: "Partners",
  help: "Help centre",
  contact: "Contact",
  "request-callback": "Request a callback",
  complaints: "Complaints",
  feedback: "Feedback",
  "report-fraud": "Report fraud",
  whistleblowing: "Whistleblowing",
  privacy: "Privacy notice",
  terms: "Terms",
  cookies: "Cookie notice",
  accessibility: "Accessibility statement",
  admin: "Website administration",
};
