import Link from "next/link";
import { BookOpen, Calculator, Printer, Share2 } from "lucide-react";
import { contentItems } from "@/mocks/fixtures";
import { formatDate } from "@/lib/format";

export function ArticlePage({ slug }: { slug: string }) {
  const item = contentItems.find((content) => content.slug === slug) ?? contentItems[0];
  return <div className="article-layout"><article className="article-body"><div className="demo-notice"><BookOpen /><span><strong>Demonstration editorial content.</strong> This guide illustrates content structure and is not individualized financial advice.</span></div><p className="eyebrow">{item.category} · {formatDate(item.publishedAt)} · {item.readingMinutes ?? 6} min read</p><h2 id="start">Start with the decision you need to make</h2><p>Good financial planning becomes easier when the goal, timing and trade-offs are visible. Begin with the outcome you want, then separate what you know from the assumptions you still need to test.</p><h2 id="cost">Look beyond the headline number</h2><p>For borrowing, an annual rate is incomplete without its method, fees and term. For saving, a projected return is incomplete without the contribution pattern, rate assumption and access conditions. A useful comparison makes those differences explicit.</p><ul><li>Write down the goal and deadline.</li><li>Use income and expense figures you can sustain.</li><li>Compare total cost or total contribution, not only the monthly number.</li><li>Keep an emergency buffer where possible.</li></ul><h2 id="test">Test a scenario, then test another</h2><p>A calculator is a planning tool, not an approval or promise. Adjust the amount, term and rate to see which assumptions most affect the outcome. If a small change creates stress, revisit the target before committing.</p><h2 id="next">Choose the next safe step</h2><p>Use approved product information, confirm official channels and ask for human support when requirements or costs are unclear. Never share a PIN, password or OTP while seeking guidance.</p><div className="security-band" style={{ marginTop: 36 }}><div><h2 style={{ fontSize: "1.6rem" }}>Turn learning into a useful estimate.</h2><p>Open a deterministic tool and keep every assumption visible.</p></div><Link className="button button--gold" href="/calculators">Explore calculators</Link></div></article><aside className="article-aside"><h2 style={{ fontSize: "1.05rem" }}>On this page</h2><nav><a href="#start">Start with the decision</a><a href="#cost">Look beyond the headline</a><a href="#test">Test scenarios</a><a href="#next">Choose the next step</a></nav><div style={{ display: "grid", gap: 8, marginTop: 22 }}><button className="button button--secondary" type="button"><Printer size={16} /> Print</button><button className="button button--secondary" type="button"><Share2 size={16} /> Share</button><Link className="button button--primary" href="/calculators"><Calculator size={16} /> Related tools</Link></div></aside></div>;
}
