import Link from "next/link";
import { ArrowRight, BookOpenCheck, Download, FileCheck2, ShieldCheck, Sparkles, Users } from "lucide-react";
import { ButtonLink, Container, DemoNotice, SectionHeader } from "@/components/ui/primitives";

type PageDefinition = { eyebrow: string; title: string; description: string; intro: string; sections: { title: string; body: string; links?: { label: string; href: string }[] }[]; cta?: { label: string; href: string } };

const definitions: Record<string, PageDefinition> = {
  membership: { eyebrow: "Membership", title: "A membership journey you can understand.", description: "Explore configurable membership paths, requirements and the full application-to-review journey.", intro: "Great 20 Sacco membership information is designed to answer the practical questions first: who a membership path is for, what may be required, how payment works and what happens during official review.", sections: [{ title: "Why membership", body: "A SACCO membership experience should make saving, access to information, shared progress and support clear without unverified promises.", links: [{ label: "Why join", href: "/membership/why-join" }] }, { title: "Choose a path", body: "Individual, joint, group/chama, corporate and diaspora paths appear only when enabled with approved rules.", links: [{ label: "Eligibility", href: "/membership/eligibility" }, { label: "Requirements", href: "/membership/requirements" }] }, { title: "See every step", body: "Contact verification, details, KYC, consent, configured fee, payment confirmation and review stay visible and distinct.", links: [{ label: "How it works", href: "/membership/how-it-works" }] }], cta: { label: "Start a demo application", href: "/join" } },
  "membership/why-join": { eyebrow: "Membership value", title: "Built around shared progress, not slogans.", description: "A clear explanation of the service model and member journey without invented institutional claims.", intro: "The final page will use approved G20 benefits and evidence. This demonstration focuses on the structure: clear value, transparent conditions, accessible support and tools that help people decide.", sections: [{ title: "Human service", body: "Move from digital guidance to an explicit callback, help or branch path when the question needs a person." }, { title: "Transparent choices", body: "Product rates always include method and context; fees and effective dates remain visible." }, { title: "Practical tools", body: "Deterministic calculators and educational guides help people understand before they apply." }], cta: { label: "Explore membership paths", href: "/membership" } },
  "membership/eligibility": { eyebrow: "Eligibility", title: "Know the rules before you start.", description: "A CMS-ready eligibility structure that will show approved requirements by membership type.", intro: "This demonstration does not invent qualifying criteria. The production page will load official, effective-dated rules from the content service and pair them with a document checklist.", sections: [{ title: "Membership-type rules", body: "Eligibility varies for individuals, joint applicants, groups, companies and diaspora members. Only enabled, approved paths appear." }, { title: "Documents and verification", body: "Identity, KRA PIN, photographs and type-specific documents appear only as configured requirements." }, { title: "Official review", body: "Passing frontend checks or paying a fee never activates membership automatically." }], cta: { label: "View requirements", href: "/membership/requirements" } },
  "membership/how-it-works": { eyebrow: "The full journey", title: "From interest to official decision.", description: "A visible, resumable process designed around mobile completion and honest status language.", intro: "The application journey groups sixteen operational moments into clear mobile steps while keeping payment and application decisions separate.", sections: [{ title: "1. Prepare and verify", body: "Choose a configured membership type, verify phone/email and review the required information." }, { title: "2. Complete details and KYC", body: "Enter schema-driven information, upload documents with progress/retry states and review every section." }, { title: "3. Consent and create the record", body: "Acknowledge approved declarations before the server creates the authoritative application reference." }, { title: "4. Pay the configured fee", body: "Use STK Push or a verified fallback. Pending, paid, failed, cancelled and reconciliation states remain distinct." }, { title: "5. Track official review", body: "Respond to change requests and wait for an explicit approval or closure status." }], cta: { label: "Start the demo journey", href: "/join" } },
  "membership/requirements": { eyebrow: "KYC preparation", title: "Bring the right documents—once.", description: "A configurable checklist with safe upload guidance and membership-type additions.", intro: "Authoritative requirements must be approved by G20. The demonstration journey can show identity/passport, KRA PIN certificate, photo and type-specific entity documents without implying every item is universally required.", sections: [{ title: "Identity", body: "Configured identity or passport evidence, collected only through the secure application upload flow." }, { title: "Tax and photograph", body: "KRA PIN certificate and a clear photo when required by the approved schema." }, { title: "Groups and entities", body: "Registration evidence, minutes, mandates and authorized signatory documents appear only for relevant application types." }, { title: "File safety", body: "Never send KYC through chat. Production uploads require size/type validation, malware scanning, secure storage and access controls." }], cta: { label: "Begin application", href: "/join" } },
  services: { eyebrow: "Member services", title: "Everyday help, without hunting for it.", description: "Digital service guidance, payment information, support and official channels in one place.", intro: "This hub is designed to reduce avoidable support friction while making escalation easy when a request needs a human.", sections: [{ title: "Digital service guidance", body: "Approved app, USSD, portal and payment instructions will appear when supplied.", links: [{ label: "Digital banking", href: "/services/digital-banking" }] }, { title: "Applications and status", body: "Start or safely track a membership application without exposing sensitive details.", links: [{ label: "Track application", href: "/application-status" }] }, { title: "Support", body: "Search help, request a callback, send feedback or open a structured complaint.", links: [{ label: "Help centre", href: "/help" }] }], cta: { label: "Ask G20", href: "/ask-g20" } },
  "services/digital-banking": { eyebrow: "Digital services", title: "Use only verified digital channels.", description: "A launch-ready structure for approved app, USSD, portal and M-Pesa instructions.", intro: "Official access links, short codes and Paybill details are intentionally absent until G20 verifies them. The page remains useful by explaining how to confirm a channel and avoid social-engineering scams.", sections: [{ title: "Before you log in", body: "Open services from verified G20 pages and check the domain or application publisher." }, { title: "Before you pay", body: "Confirm the official payment destination, account reference and exact amount." }, { title: "Protect credentials", body: "No staff member or chat should request your PIN, password or one-time code." }], cta: { label: "Security centre", href: "/security" } },
  help: { eyebrow: "Help centre", title: "Find the answer—or the right person.", description: "Search top tasks, product questions, application help, digital-service support and safety guidance.", intro: "Help content remains useful when Ask G20 is unavailable. Each topic can route to a verified page, calculator or explicit human handoff.", sections: [{ title: "Top tasks", body: "Start membership, track an application, estimate a repayment, find a service point or report a security concern.", links: [{ label: "Application status", href: "/application-status" }, { label: "Calculators", href: "/calculators" }] }, { title: "Product help", body: "Understand eligibility, documents, rate methods, fees, terms and the difference between estimates and decisions.", links: [{ label: "Savings", href: "/save" }, { label: "Borrowing", href: "/borrow" }] }, { title: "Contact support", body: "Use a structured enquiry, callback or complaints path.", links: [{ label: "Contact", href: "/contact" }, { label: "Request callback", href: "/request-callback" }] }], cta: { label: "Ask G20", href: "/ask-g20" } },
  security: { eyebrow: "Security centre", title: "Stop. Check. Protect.", description: "Practical guidance for payments, phishing, SIM-swap risk, passwords, OTPs and official channels.", intro: "The production security centre will publish only verified G20 channels and current alerts. Until then, the safest design choice is to omit unverified Paybill, Till, phone and regulator details.", sections: [{ title: "G20 will never ask", body: "Never share an M-Pesa PIN, password or one-time code with a caller, message, website form or AI assistant." }, { title: "Verify before paying", body: "Use only approved official channels and compare the recipient and amount shown on your phone." }, { title: "If your SIM changes unexpectedly", body: "Contact your mobile provider through a verified route, secure financial accounts and report suspicious activity." }, { title: "Report suspected fraud", body: "Preserve evidence, avoid further contact with the suspected party and use the dedicated reporting route.", links: [{ label: "Report fraud", href: "/report-fraud" }] }], cta: { label: "View official-channel guidance", href: "/contact" } },
  transparency: { eyebrow: "Transparency", title: "Documents, dates and claims you can verify.", description: "A governance-ready centre for approved reports, publications and regulator links.", intro: "No leadership, regulatory, audit or impact claim is invented in this demonstration. Production records require approved titles, dates, file metadata and verification links.", sections: [{ title: "Reports and statements", body: "Annual reports, audited statements and AGM publications use searchable metadata and accessible downloads.", links: [{ label: "Reports", href: "/reports" }] }, { title: "Governance", body: "Approved governance structures and policies are published with effective or review dates.", links: [{ label: "Governance", href: "/about/governance" }] }, { title: "Impact", body: "Only reviewed metrics with definitions, periods and sources can appear.", links: [{ label: "Impact", href: "/about/impact" }] }], cta: { label: "Browse downloads", href: "/downloads" } },
  about: { eyebrow: "About G20", title: "Institutional information, built for evidence.", description: "A structured home for approved history, mission, leadership, governance and impact.", intro: "This frontend supplies the editorial architecture without inventing G20’s history, board, regulatory position or performance.", sections: [{ title: "History", body: "A dated timeline can tell the approved institutional story.", links: [{ label: "View history", href: "/about/history" }] }, { title: "Mission and values", body: "Approved mission, vision and values belong in managed content with review ownership.", links: [{ label: "Mission and values", href: "/about/mission" }] }, { title: "Leadership and governance", body: "Profiles and governance information render only from verified records.", links: [{ label: "Leadership", href: "/about/leadership" }, { label: "Governance", href: "/about/governance" }] }], cta: { label: "Transparency centre", href: "/transparency" } },
  privacy: { eyebrow: "Legal placeholder", title: "Privacy notice structure.", description: "A launch-ready page awaiting approved legal text, controller details, lawful bases and retention periods.", intro: "This demonstration states the intended architecture, not G20’s final legal notice.", sections: [{ title: "Information and purpose", body: "Explain each category collected, why it is needed and whether it is required." }, { title: "Sharing and storage", body: "Identify approved processors, transfers, security measures and retention schedules." }, { title: "Your choices and rights", body: "Provide verified request channels, consent controls and complaint routes." }], cta: { label: "Contact about privacy", href: "/contact" } },
  terms: { eyebrow: "Legal placeholder", title: "Website terms structure.", description: "A clear structure awaiting approved G20 legal terms.", intro: "Production terms will cover website use, information limitations, calculator estimates, intellectual property, availability and governing terms.", sections: [{ title: "Information, not advice", body: "Explain the status of educational content, estimates and preliminary recommendations." }, { title: "Applications and decisions", body: "Clarify that form submission and payment do not guarantee membership or credit approval." }, { title: "Acceptable use", body: "Set rules for lawful, secure use of digital services." }] },
  cookies: { eyebrow: "Privacy controls", title: "Cookie and consent choices.", description: "Essential, preference, analytics and marketing categories with consent-aware loading.", intro: "Non-essential analytics should not load before the applicable consent choice. Lite Mode is stored as a local preference and does not require marketing tracking.", sections: [{ title: "Strictly necessary", body: "Security, load balancing, session and consent-state functions required for the service." }, { title: "Preferences", body: "Language, Lite Mode and accessibility preferences when enabled." }, { title: "Analytics and marketing", body: "Load only under the approved policy and never include sensitive application or payment details." }] },
  accessibility: { eyebrow: "Accessibility", title: "Designed for more ways of using the web.", description: "A WCAG 2.2 AA target with keyboard access, focus visibility, zoom support and assistive status updates.", intro: "The statement will be updated with tested conformance, known limitations, contact routes and remediation dates before production launch.", sections: [{ title: "What the frontend supports", body: "Semantic landmarks, a skip link, logical headings, 44px targets, visible focus, form labels, error focus, live regions and reduced motion." }, { title: "Mobile and zoom", body: "Critical journeys are designed from 320px upward and should remain usable at 200% text zoom without two-dimensional scrolling." }, { title: "Report a barrier", body: "Use the contact route to describe the page, task, device and assistive technology involved.", links: [{ label: "Contact support", href: "/contact" }] }] },
};

const collectionCopy: Record<string, { title: string; description: string; category: string }> = {
  learn: { title: "Build money confidence, one practical guide at a time.", description: "Saving, borrowing, SACCO basics, business finance, retirement, education and fraud-prevention guides.", category: "Financial education" },
  blog: { title: "Ideas for practical financial progress.", description: "Editorial articles with sources, dates, related tools and print-ready layouts.", category: "Blog" },
  news: { title: "Official G20 news, when approved.", description: "A verified newsroom with publication and update dates.", category: "Newsroom" },
  events: { title: "Events worth planning for.", description: "AGMs, education sessions and member events with status and date metadata.", category: "Events" },
  notices: { title: "Notices that expire when they should.", description: "Priority-aware official notices with severity and expiration.", category: "Official notices" },
  media: { title: "Media resources with verified context.", description: "Approved press materials, galleries and video links.", category: "Media centre" },
  stories: { title: "Member stories only with approval.", description: "No fabricated testimonials—only approved case studies with consent.", category: "Stories" },
  reports: { title: "Reports and statements you can verify.", description: "Accessible annual, audited and AGM publications when supplied.", category: "Reports" },
  downloads: { title: "Forms, policies and publications.", description: "Searchable downloads with file type, size, date and accessible description.", category: "Downloads" },
  careers: { title: "Build a career with shared purpose.", description: "Approved vacancies, fair application guidance and verified links.", category: "Careers" },
  procurement: { title: "Transparent supplier opportunities.", description: "Verified tenders, deadlines, documents and submission instructions.", category: "Procurement" },
  partners: { title: "Partnerships shown only when verified.", description: "Approved partner information without invented logos or endorsements.", category: "Partners" },
};

export function GenericPage({ route }: { route: string }) {
  const definition = definitions[route];
  if (definition) return <><section className="section"><Container><DemoNotice /><p className="page-hero__lead" style={{ maxWidth: 780 }}>{definition.intro}</p><div className="card-grid card-grid--three" style={{ marginTop: 34 }}>{definition.sections.map((section, index) => { const icons = [Sparkles, FileCheck2, ShieldCheck, Users]; const Icon = icons[index % icons.length]; return <article className="feature-card" key={section.title}><Icon color="var(--brand)" /><h2 style={{ fontSize: "1.45rem", marginTop: 22 }}>{section.title}</h2><p>{section.body}</p>{section.links?.map((link) => <Link key={link.href} className="product-card__link" href={link.href}>{link.label} <ArrowRight size={16} /></Link>)}</article> })}</div>{definition.cta && <div style={{ marginTop: 34 }}><ButtonLink href={definition.cta.href}>{definition.cta.label}</ButtonLink></div>}</Container></section></>;

  const key = route.split("/")[0];
  const collection = collectionCopy[key] ?? { title: "Clear information, ready for approved content.", description: "This route uses structured, reviewable content and explicit verification states.", category: "G20 digital branch" };
  return <section className="section"><Container><DemoNotice /><SectionHeader eyebrow={collection.category} title={collection.title} description={collection.description} /><div className="card-grid card-grid--three">{[
    { icon: BookOpenCheck, title: "Structured for understanding", body: "Content uses plain language, publication metadata, related actions and accessible hierarchy." },
    { icon: FileCheck2, title: "Approval is visible", body: "Demo, draft, published, expired and archived states remain distinct in the content model." },
    { icon: Download, title: "Useful on mobile", body: "Downloads show format, size and context; long articles support table of contents and print view." },
  ].map(({ icon: Icon, title, body }) => <article className="feature-card" key={title}><Icon color="var(--brand)" /><h2 style={{ fontSize: "1.4rem", marginTop: 22 }}>{title}</h2><p>{body}</p></article>)}</div><div style={{ marginTop: 34, display: "flex", flexWrap: "wrap", gap: 9 }}><ButtonLink href="/learn">Browse education</ButtonLink><ButtonLink href="/ask-g20" variant="secondary">Ask G20</ButtonLink></div></Container></section>;
}

export function getDefinition(route: string): PageDefinition | undefined { return definitions[route]; }
export function getCollectionDefinition(route: string) { return collectionCopy[route.split("/")[0]]; }
